
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported Fields

[partintro]

--
This document describes the fields that are exported by Nvidiagpubeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-nvidiagpubeat>>

--
[[exported-fields-beat]]
== Beat Fields

Contains common beat fields available in all event types.



[float]
=== beat.name

The name of the Beat sending the log messages. If the Beat name is set in the configuration file, then that value is used. If it is not set, the hostname is used. To set the Beat name, use the `name` option in the configuration file.


[float]
=== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[float]
=== beat.version

The version of the beat that generated this event.


[float]
=== @timestamp

type: date

example: August 26th 2016, 12:35:53.332

format: date

required: True

The timestamp when the event log record was generated.


[float]
=== tags

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== fields

type: dict

Contains user configurable fields.


[[exported-fields-nvidiagpubeat]]
== nvidiagpubeat Fields

None


[float]
=== gpu.id

type: text

required: True

Identifier for the GPU

[float]
=== gpu.frame_buffer_total_mb

type: float

required: True

Total frame buffer memory for the GPU

[float]
=== gpu.frame_buffer_used_mb

type: float

required: True

Used frame buffer memory for the GPU

[float]
=== gpu.frame_buffer_free_mb

type: float

required: True

Free frame buffer memory for the GPU

[float]
=== gpu.bar1_total_mb

type: float

required: True

Total BAR1 memory for the GPU

[float]
=== gpu.bar1_used_mb

type: float

required: True

Used BAR1 memory for the GPU

[float]
=== gpu.bar1_free_mb

type: float

required: True

Free BAR1 memory for the GPU

[float]
=== gpu.processor_utilization_pct

type: float

required: True

Utilization measurement for the GPU

[float]
=== gpu.memory_utilization_pct

type: float

required: True

Memory utilization measurement for the GPU

